### ISSUE TITLE
Ensure that lib directories are added to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiconda#14]
Make sure that the conda lib directory is added to `LD_LIBRARY_PATH` in addition to the aux lib directory.  See desihub/desiconda#13.

**Comment by tskisner** [comment]
Actually this should never be done.  The conda lib directory contains incompatible libraries (tcl, hdf5, etc) that shadow system libraries.  Adding the conda lib directory to LD_LIBRARY_PATH breaks things like modules.  In fact, this was the original reason for having the "aux" directory in the first place (so that we could put stuff in LD_LIBRARY_PATH without bringing in all of the conda libraries.

**Comment by weaverba137** [comment]
OK, fair enough.  And also I put the wrong issue link in the original report.  I was trying to reference desihub/desimodules#13, where a bug was fixed by explicitly adding the conda lib directory to `LD_LIBRARY_PATH`.  Can you please take a look at that?

**Comment by weaverba137** [comment]
Based on this discussion, I'm labeling this as 'wontfix'.  Feel free to close.

**Comment by tskisner** [comment]
Yes, that desiconda should really, really not be used any more.  It has other fundamental problems since it was created before we understood the perils of mixing gcc + MKL + python.  Hopefully soon we'll move to the latest desiconda from 01/30/2018.
