### ISSUE TITLE
Update to fitsio 1.0.5

### ISSUE THREAD

**Issue by dkirkby** [desihub/desiconda#37]
It looks like the DESI conda env (and corresponding jupyter kernel) use fitsio 0.9.5:
```
> source /project/projectdirs/desi/software/desi_environment.sh master
> python -c 'import fitsio; print(fitsio.__version__)'
0.9.11
```

GFA data written since 20191208 cannot be read with 0.9.11 (for unknown reasons) but the latest 1.0.5 can read old and new GFA data.

To reproduce the problem reading recent GFA data with 0.9.11:
```
import fitsio
fitsio.read_header('/project/projectdirs/desi/spectro/data/20191212/00031386/gfa-00031386.fits.fz', ext='FOCUS1')
```
which results in `OSError: FITSIO status = 204: keyword value is undefined`.

**Comment by moustakas** [comment]
Not sure if we use any compression, but we should be aware of this issue--
https://github.com/esheldon/fitsio/issues/283

**Comment by daqiii** [comment]
David,
The online system went to fitsio 1.05 a week or two ago
Klaus

Sent from my iPhone

On Dec 15, 2019, at 9:58 AM, David Kirkby <notifications@github.com> wrote:

﻿

It looks like the DESI conda env (and corresponding jupyter kernel) use fitsio 0.9.5:

> source /project/projectdirs/desi/software/desi_environment.sh master
> python -c 'import fitsio; print(fitsio.__version__)'
0.9.11


GFA data written since 20191208 cannot be read with 0.9.11 (for unknown reasons) but the latest 1.0.5 can read old and new GFA data.

To reproduce the problem reading recent GFA data with 0.9.11:

import fitsio
fitsio.read_header('/project/projectdirs/desi/spectro/data/20191212/00031386/gfa-00031386.fits.fz', ext='FOCUS1')


which results in OSError: FITSIO status = 204: keyword value is undefined.

**Comment by sbailey** [comment]
done in PR #40 and tag 1.4.0
