### ISSUE TITLE
Load cudatoolkit on Perlmutter

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/desiconda#51]
GPU-enabled code requires 
```
module load cudatoolkit
```
on Perlmutter, but this is not yet handled automatically. 

Likely the best solution is to add code somewhere in modulefile.gen so that the cudatoolkit module is loaded in the desiconda module file for installations on Perlmutter.

**Comment by marcelo-alvarez** [comment]
@dmargala @sbailey the current agreed-upon solution is to avoid conflicts between the desiconda
`cudatoolkit` installation and the NERSC-provided one (since the latter is now loaded by default at NERSC) by executing `module unload `cudatoolkit` explicitly in the `desimodules` module file. We will be missing the "extras" (such as profiling and build tools) available with the NERSC-provided `cudatoolkit` module. It remains to be seen whether it's possible to either 
- load those extras separately via NERSC-provided modules, and expect them to be compatible
or instead
- install those extras ourselves in the desiconda environment via, e.g., conda-forge.

We can consider this issue resolved once functioning  "cudatoolkit extras" are available by default in the desiconda environment.

**Comment by sbailey** [comment]
to get the extras (e.g. nsys profiler) without the full cudatoolkit:
```
module load Nsight-Systems
```
I'm going to remove this from the Iron project, but leave it open pending a decision about whether this is robust enough to become part of the default environment, or otherwise whether we should go back to using NERSC-provided toolkit, or leave things as-is (Nsight-Systems available, but not loaded by default).
