### ISSUE TITLE
Add fpoffline package

### ISSUE THREAD

**Issue by dkirkby** [desihub/desiconda#52]
I would like to include `desihub/fpoffline` in the list of DESI packages used by desiconda.

Shall I make a PR with this added to `scripts/bootstrap-desi.sh` or is there a different procedure?

**Comment by sbailey** [comment]
I ran `desiInstall fpoffline main` as the desi user to install it as a module; please try `module load fpoffline` and try using it to see if it is configured correctly (it passes basic ability to load the module, but other that that I don't know what to try).

If that works, you can then add it to scripts/bootstrap-desi.sh to be included by default in future desiconda releases.  When you make tags, we can also install those.

**Comment by dkirkby** [comment]
Thanks.  I tested that I can import and run `fpoffline` modules, but it looks like the executable script generated by `pip install .` (via setup.py entry_points) is not created or, at least, not visible via $PATH.

Looking desimeter, it seems that executable scripts need to be under a top-level bin/ folder?  Is there a way to accomplish that and still use the setup.py entry_points machinery?

**Comment by dkirkby** [comment]
I should make a tag anyway and it sounds like this would fix the problem?

**Comment by sbailey** [comment]
it would fix the problem (I think) for the purposes of the tagged installation, though the main installation would remain without the executables.  Please ping me when the tag is ready and we'll try that and then iterate if the tag installation is also broken.

**Comment by weaverba137** [comment]
@sbailey, @dkirkby, it sounds like the solution was to install fpoffline with desiInstall.  Is that fully implemented?

**Comment by weaverba137** [comment]
Since it's been a year, I'll ask again: @sbailey, @dkirkby, it sounds like the solution was to install fpoffline with desiInstall. Is that fully implemented?

**Comment by sbailey** [comment]
We never got far enough to include fpoffline in scripts/bootstrap-desi.sh, and it looks like fpoffline isn't updated to use a bin/ directory with script wrappers instead of entry_points, and it doesn't have any tags so we haven't tested that either.  I think that is a small refactor, but given how old this ticket is I suspect it hasn't been high priority.

@dkirkby if this is something you still want, please update fpoffline to have scripts in a bin/ directory (to support desiInstall installations of main) and/or make a fpoffline tag that we can test for a tag installation.

**Comment by dkirkby** [comment]
Thanks for following up on this @sbailey and @weaverba137.  Now that I understand how desiInstall works a bit better, I prefer to stick with the python-standard entry_points mechanism since that is probably more convenient for most users of this package. I will close this issue now.
