### ISSUE TITLE
Bootstrap script does not use desiutil bootstrap method

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiconda#56]
The `scripts/bootstrap-desi.sh` script should use the `desiBootstrap.sh` script to actually install `desiutil` so that subsequent packages can be installed with `desiInstall`.  This will prevent desiutil from being installed as both a `pip` package *and* a `desiInstall`ed package.

This is similar to #53 .

**Comment by sbailey** [comment]
Although it's a bit unusual to pip install desiutil, use it for desiInstall, and then pip uninstall it (because a module version of desiutil was installed in the meantime), I believe the existing `scripts/bootstrap-desi.sh` script works (other than the unrelated master vs. main) and I suggest that we leave it as-is unless there is a specific problem with it that desiutil/bin/desiBootstrap.sh already fixes.

Note that the final state does not leave a pip-installed desiutil behind, unlike #53 where we simply forgot to remove speclite from the list of pip installed packages after promoting it to a module.

**Comment by weaverba137** [comment]
Ah, I missed the part where it is uninstalled. I'll leave this as a non-bug then to think about further.
